version: '2'
services:
  app:
    build: ./src
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: postgres:latest
    container_name: db_devcamp
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devcamp
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080